package module.two.hashing.one.notes;

import java.util.Arrays;
import java.util.LinkedList;
import java.util.Objects;

/**
 * Basics of Hashing
 * Hashing is a technique used to efficiently map a large amount of data to a smaller table using a "hash function." This
 * method allows for quicker and more efficient data searching compared to other techniques like linear and binary search.
 * Hashing uniquely identifies specific items from a collection of similar items by using hash tables, which store data in an
 * array format. Each value in the array is assigned a unique index number generated by the hash function. By finding the
 * index of the desired item, you can quickly access the data without scanning the entire list, which also helps in efficient
 * data insertion.
 * <p>
 * Key Concepts in Hashing:
 * <p>
 * --> Hash Function: Converts an item into a small integer (hash value). This integer is used as an index to store the original
 * data.
 * --> Hash Table: Stores key-value pairs in an array format. It uses the hash function to generate an index.
 * --> Buckets: Slots in the hash table where data is stored. Each bucket can store one or more key-value pairs.
 * --> Collision: Occurs when two different keys produce the same hash value and thus map to the same bucket.
 * Process of Hashing:
 * <p>
 * Hashing in data structures is a two-step process:
 * <p>
 * - Hash Function Calculation: The hash function converts the item into a small integer or hash value.
 * --> Example: hash = hashfunc(key)
 * --> Index calculation: index = hash % array_size
 * - Data Storage: The data is stored in a hash table using the hash value as the index.
 * --> Example: array[index] = value
 * Requirements for a Good Hash Function:
 * <p>
 * - Ease of Computation: The hash function should be easy to compute.
 * - Uniform Distribution: It should distribute keys evenly across the hash table to avoid clustering.
 * - Collision Avoidance: It should minimize the chances of collisions, where two items are assigned the same hash value.
 * Collision Resolution Techniques:
 * <p>
 * Collisions in a hash table need to be managed to maintain performance. The primary collision resolution techniques are:
 * <p>
 * - Open Hashing (Separate Chaining):
 * --> Each bucket points to a linked list of entries that map to the same index.
 * --> Example: If keys "dog" and "god" produce the same hash code, both entries will be stored in the same bucket but in a
 * linked list.
 * - Closed Hashing (Open Addressing):
 * --> Instead of storing multiple entries in the same bucket, closed hashing searches for another bucket within the table
 * using a probing sequence.
 * Types of Open Addressing:
 * <p>
 * - Linear Probing:
 * --> If a collision occurs at index hash(n) % T, the algorithm checks the next bucket: (hash(n) + 1) % T.
 * --> Continues until an empty bucket is found.
 * --> Example:
 * If slot index = (hash(n) % T) is full, try (hash(n) + 1) % T, (hash(n) + 2) % T, etc.
 * Load Factor: Represents the load on the hash table. It is the ratio n/b, where n is the number of entries and b is the size
 * of the array. A low load factor ensures that the number of entries at one index is less, maintaining a complexity of O(1).
 * - Quadratic Probing:
 * --> The algorithm checks buckets in a quadratic sequence: (hash(n) + 1^2) % T, (hash(n) + 2^2) % T, etc.
 * --> Reduces clustering compared to linear probing.
 * - Double Hashing:
 * --> Uses a second hash function to determine the step size for probing.
 * --> If a collision occurs, the next index is determined by: index = (hash1(key) + i * hash2(key)) % array_size.
 * <p>
 * Time Complexity Analysis
 * 1.Insertion:
 * Average Case: O(1 + α)
 * Where α (load factor) = n / m (n is the number of elements, and m is the size of the hash table).
 * Worst Case: O(n)
 * When all elements hash to the same bucket, create a single linked list.
 * <p>
 * 2.Deletion:
 * Average Case: O(1 + α)
 * Similar to insertion, it involves finding the element and removing it.
 * Worst Case: O(n)
 * When all elements hash to the same bucket, creating a single linked list, and the element to be deleted is at the end.
 * <p>
 * 3.Search:
 * Average Case: O(1 + α)
 * Similar to insertion and deletion.
 * Worst Case: O(n)
 * When all elements hash to the same bucket.
 * <p>
 * Load Factor (α):
 * The load factor is defined as α = n / m, where:
 * n = Total number of elements in the hash table.
 * m = Size of the hash table.
 * A low load factor means fewer elements per bucket, leading to faster operations (O(1 + α)).
 * A high load factor increases the likelihood of collisions, leading to slower operations.
 * <p>
 * Use Cases of Hashing
 * <p>
 * Data Retrieval
 * Hashing is a powerful technique for efficient data retrieval, particularly in applications where quick access to data is
 * crucial. By converting object data into a useful integer value using algorithms or functions, hashing facilitates the
 * organization and filtering of queries.
 * For instance, in hash tables, developers store data, such as customer records, as key-value pairs. The hash function maps
 * keys to integers of a predetermined size, allowing for fast data retrieval based on these hash codes. This method is widely
 * used in various applications, from databases to caching systems, where speed and efficiency are paramount.
 * <p>
 * Digital Signatures
 * Hashing plays a critical role in the encryption and decryption processes involved in digital signatures, ensuring the
 * authenticity and integrity of messages. When creating a digital signature, a hash function transforms the signature into a
 * hashed value or message digest, which is then transmitted separately to the recipient. Upon receiving the message, the same
 * hash function is applied to the signature to generate a message digest. This digest is compared to the transmitted message
 * digest to verify their match, confirming the sender's identity and the message's integrity. This one-way hashing operation
 * securely indexes the initial value or key, making the associated data accessible while maintaining security. Hashing,
 * therefore, is essential in secure communication protocols, ensuring that digital signatures are both valid and trustworthy.
 */
public class CustomHashTable<T> {

    private final int buckets;
    private LinkedList<T>[] table;

    public CustomHashTable(int size) {
        this.buckets = size;
        table = new LinkedList[size];
        for (int i = 0; i < size; i++) {
            table[i] = new LinkedList<>();
        }
    }

    private int hashFunction(T key) {
        return Objects.hash(key) % this.buckets;
    }

    public boolean containsKey(T key) {
        int index = this.hashFunction(key);
        if (index > this.buckets) {
            return false;
        }
        return this.table[index].contains(key);
    }

    public boolean add(T key) {
        if (containsKey(key)) {
            return false;
        }
        int index = this.hashFunction(key);
        this.table[index].add(key);
        return true;
    }

    public T remove(T key) {
        int index = this.hashFunction(key);
        if (index > this.buckets) {
            return null;
        }
        this.table[index].remove(key);
        return key;
    }

    @Override
    public String toString() {
        return "customHashSet { " + Arrays.toString(this.table) + " }";
    }

    public static void main(String[] args) {
        integerSet();
        stringSet();
    }

    private static void integerSet() {
        CustomHashTable<Integer> integerSet = new CustomHashTable<>(5);
        integerSet.add(10);
        integerSet.add(11);
        integerSet.add(15);
        integerSet.add(14);
        integerSet.add(10);
        System.out.println(integerSet);
        integerSet.remove(10);
        integerSet.remove(14);
        System.out.println(integerSet);
        System.out.println(integerSet.containsKey(15));
        System.out.println(integerSet.containsKey(150));
        System.out.println();
    }

    private static void stringSet() {
        CustomHashTable<String> stringSet = new CustomHashTable<>(5);
        stringSet.add("hello");
        stringSet.add("world");
        stringSet.add("how");
        stringSet.add("are");
        stringSet.add("you");
        stringSet.add("are");
        System.out.println(stringSet);
        stringSet.remove("how");
        stringSet.remove("there");
        System.out.println(stringSet);
        System.out.println(stringSet.containsKey("world"));
        System.out.println(stringSet.containsKey("w"));
        System.out.println();
    }

}
